# Generated by Django 5.2.4 on 2026-03-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hades_app", "0009_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="formtemplate",
            name="is_persistent",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, el formulario reaparece como pendiente tras completarse",
            ),
        ),
        migrations.AlterField(
            model_name="formanswers",
            name="clave_eds_fk",
            field=models.CharField(
                blank=True,
                help_text="Clave de la EDS donde se respondió (cod_eds en erelis)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formanswers",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Archivo de imagen 1 de la respuesta",
                null=True,
                upload_to="form_answers/",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="clave_eds_fk",
            field=models.CharField(
                blank=True,
                help_text="Clave de la EDS asignada (cod_eds en erelis)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="clave_eds",
            field=models.CharField(
                blank=True,
                help_text="Clave de la EDS asignada (cod_eds en erelis)",
                max_length=20,
                null=True,
            ),
        ),
    ]
