"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import json
from dotenv import load_dotenv, dotenv_values
from pathlib import Path

# Modelo de usuario personalizado
AUTH_USER_MODEL = "hades_app.Users"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# === Elegir entorno: dev o prod ===
DEFAULT_DJANGO_ENV = "dev"
ENV_FILE_MAP = {
    "dev": ".env.dev",
    "prod": ".env.prod",
    "docker": ".env.docker",
}

DJANGO_ENV = (os.getenv("DJANGO_ENV") or DEFAULT_DJANGO_ENV).strip().lower()

if DJANGO_ENV not in ENV_FILE_MAP:
    DJANGO_ENV = DEFAULT_DJANGO_ENV

os.environ["DJANGO_ENV"] = DJANGO_ENV


def _resolve_env_path(filename: str) -> Path:
    candidate = Path(filename)
    if not candidate.is_absolute():
        candidate = BASE_DIR / candidate
    return candidate


env_file_candidates = []

explicit_env_file = os.getenv("DJANGO_ENV_FILE")
if explicit_env_file:
    env_file_candidates.append(_resolve_env_path(explicit_env_file))

base_env_file = _resolve_env_path(ENV_FILE_MAP[DJANGO_ENV])
local_env_file = base_env_file.with_name(f"{base_env_file.name}.local")

env_file_candidates.extend([local_env_file, base_env_file])

env_file = next((path for path in env_file_candidates if path.exists()), base_env_file)

env_values = dotenv_values(env_file)


def env(key, default=None):
    """Devuelve variables dando prioridad al archivo del entorno seleccionado."""

    if key in env_values and env_values[key] is not None:
        return env_values[key]
    return os.getenv(key, default)


# override=True para que al cambiar de entorno no se queden valores previos en memoria
load_dotenv(env_file, override=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")


# === DEV/PROD TOGGLES Y ORIGINS ===
FORCE_HTTPS = env("FORCE_HTTPS", "false").lower() == "true"
DEBUG = env("DEBUG", "true").lower() == "true"
FRONT_ORIGIN = env("FRONT_ORIGIN", "http://localhost:4200")
API_ORIGIN = env("API_ORIGIN", "http://localhost:8000")
DOMAIN = env("COOKIE_DOMAIN", None)

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    env("HOST", ""),
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "cache-control",  # Este es el que falta
    "ngsw-bypass",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]


SESSION_COOKIE_DOMAIN = None


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "drf_yasg",
    "hades_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",  # Reactivado
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "server.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}

# Configuración opcional para base externa de EDS
EDS_DB_TABLE = env("EDS_DB_TABLE", "oasis_cat_eds")
EDS_PROFILE_FALLBACK = env("EDS_SOURCES", "erelis,oasis")
EDS_REQUESTED_PROFILE = (
    (env("EDS_PROFILE") or env("EDS_ACTIVE_SOURCE") or "").strip().lower()
)


def _build_eds_connection(prefix):
    """Arma la configuración de conexión tomando un prefijo de variables."""

    name = env(f"{prefix}_NAME")
    if not name:
        return None

    return {
        "ENGINE": env(f"{prefix}_ENGINE", "hades_app.db_backends.postgres_compat"),
        "NAME": name,
        "USER": env(f"{prefix}_USER"),
        "PASSWORD": env(f"{prefix}_PASSWORD"),
        "HOST": env(f"{prefix}_HOST"),
        "PORT": env(f"{prefix}_PORT"),
        "OPTIONS": {
            k: v for k, v in {"sslmode": env(f"{prefix}_SSLMODE")}.items() if v
        },
    }


def _build_eds_connection_from_json(profile):
    """Carga la configuración desde un JSON (útil para llaves de servicio)."""

    json_path = env(f"EDS_{profile.upper()}_DB_JSON")
    if not json_path:
        return None

    candidate = Path(json_path)
    if not candidate.is_absolute():
        candidate = BASE_DIR / candidate

    if not candidate.exists():
        raise RuntimeError(f"EDS json no encontrado: {candidate}")

    try:
        with candidate.open("r", encoding="utf-8") as fp:
            payload = json.load(fp)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"EDS json inválido: {candidate}") from exc

    def pick(*keys):
        for key in keys:
            if key in payload and payload[key] not in (None, ""):
                return payload[key]
        return None

    config = {
        "ENGINE": pick("engine", "ENGINE") or "hades_app.db_backends.postgres_compat",
        "NAME": pick("name", "database", "db_name", "NAME"),
        "USER": pick("user", "username", "client_email", "USER"),
        "PASSWORD": pick("password", "private_key", "PASSWORD"),
        "HOST": pick("host", "HOST"),
        "PORT": pick("port", "PORT"),
        "OPTIONS": {
            k: v
            for k, v in {"sslmode": pick("sslmode", "SSL_MODE", "ssl")}.items()
            if v
        },
    }

    if not config["NAME"]:
        return None

    return config


eds_connections = {}

# Compatibilidad con las variables heredadas (EDS_DB_*)
legacy_connection = _build_eds_connection("EDS_DB")
if legacy_connection:
    eds_connections["legacy"] = legacy_connection

raw_profile_order = [
    s.strip().lower() for s in EDS_PROFILE_FALLBACK.split(",") if s.strip()
]

for source in raw_profile_order:
    if source == "legacy":
        continue

    prefix = f"EDS_{source.upper()}_DB"
    config = _build_eds_connection(prefix)
    if not config:
        config = _build_eds_connection_from_json(source)
    if config:
        eds_connections[source] = config

EDS_AVAILABLE_SOURCES = tuple(eds_connections.keys())

if eds_connections:
    if EDS_REQUESTED_PROFILE and EDS_REQUESTED_PROFILE in eds_connections:
        selected_key = EDS_REQUESTED_PROFILE
    else:
        selected_key = next(iter(eds_connections.keys()))

    DATABASES["eds"] = eds_connections[selected_key]
    EDS_ACTIVE_SOURCE = selected_key
else:
    EDS_ACTIVE_SOURCE = None


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-es"  # Changed to Spanish

TIME_ZONE = "America/Mexico_City"  # Adjust according to your timezone

USE_I18N = True

USE_TZ = True


# Django REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",  # Cambia a IsAuthenticated en prod
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================================

# === CORS Y COOKIES SEGÚN RECETA ===
CORS_ALLOWED_ORIGINS = [
    FRONT_ORIGIN,
    FRONT_ORIGIN.replace("http://", "https://"),
    API_ORIGIN,
    API_ORIGIN.replace("http://", "https://"),
]
CORS_ALLOW_CREDENTIALS = True

# Cookies de sesión/CSRF
SESSION_COOKIE_HTTPONLY = True
# Cookies deben viajar entre frontend/back distintos -> SameSite=None + Secure
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_DOMAIN = DOMAIN  # None en local; ".midominio.com" en prod
SESSION_COOKIE_AGE = 1209600
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = [
    FRONT_ORIGIN,
    FRONT_ORIGIN.replace("http://", "https://"),
    API_ORIGIN,
    API_ORIGIN.replace("http://", "https://"),
]

if FORCE_HTTPS:
    # Cloud Run envía X-Forwarded-Proto=https; indicamos a Django que confíe en él
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Ruteo de bases de datos
DATABASE_ROUTERS = ["hades_app.db_routers.EDSRouter"] if "eds" in DATABASES else []
