CREATE TABLE "Users" (
	"id_usr_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(65),
	"email" VARCHAR(30),
	"password" VARCHAR(100),
	"usr_status" BOOLEAN,
	"id_role_fk" INTEGER,
	"id_eds_fk" INTEGER,
	"id_work_area_fk" INTEGER,
	PRIMARY KEY("id_usr_pk")
);




CREATE TABLE "Roles" (
	"id_rol_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(20),
	"created_at" DATE,
	"updated_at" DATE,
	"usr_created_at" VARCHAR(65),
	"usr_updated_at" VARCHAR(65),
	"id_permission_fk" INTEGER,
	"role_status" BOOLEAN,
	PRIMARY KEY("id_rol_pk")
);




CREATE TABLE "Permissions" (
	"id_permissions_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(20),
	"created_at" DATE,
	"updated_at" DATE,
	"usr_created_at" VARCHAR(65),
	"usr_updated_at" VARCHAR(65),
	"permission_status" BOOLEAN,
	PRIMARY KEY("id_permissions_pk")
);




CREATE TABLE "WorkArea" (
	"id_work_area_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(65),
	"created_at" DATE,
	"updated_at" DATE,
	"usr_created_at" VARCHAR(255),
	"usr_updated_at" VARCHAR(255),
	PRIMARY KEY("id_work_area_pk")
);




CREATE TABLE "WorkOrder" (
	"id_work_order_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"date" DATE,
	"status" VARCHAR(65),
	"id_usr_fk" INTEGER,
	"id_eds_fk" INTEGER,
	"dsc" VARCHAR(65),
	"image" VARCHAR(65),
	"id_question_form_fk" INTEGER,
	"name" VARCHAR(65),
	"start_date_time" DATE,
	"end_date_time" DATE,
	"id_work_area_fk" INTEGER,
	PRIMARY KEY("id_work_order_pk")
);




CREATE TABLE "EDS" (
	"id_eds_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(65),
	"plaza" VARCHAR(20),
	"state" VARCHAR(20),
	"municipality" VARCHAR(35),
	"zip_code" VARCHAR(10),
	"plaza_status" BOOLEAN,
	"long_eds" NUMERIC,
	"latit_eds" NUMERIC,
	PRIMARY KEY("id_eds_pk")
);




CREATE TABLE "FormQuestions" (
	"id_question_form_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"question" VARCHAR(65),
	"is_required" BOOLEAN,
	"type" VARCHAR(65),
	PRIMARY KEY("id_question_form_pk")
);




CREATE TABLE "FormAnswers" (
	"id_answer_form_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_question_form_fk" INTEGER,
	"answer" BOOLEAN,
	"area" VARCHAR(50),
	"comments" VARCHAR(100),
	"image" VARCHAR(65),
	PRIMARY KEY("id_answer_form_pk")
);



ALTER TABLE "Users"
ADD FOREIGN KEY("id_role_fk") REFERENCES "Roles"("id_rol_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Roles"
ADD FOREIGN KEY("id_permission_fk") REFERENCES "Permissions"("id_permissions_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Users"
ADD FOREIGN KEY("id_eds_fk") REFERENCES "EDS"("id_eds_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "WorkOrder"
ADD FOREIGN KEY("id_usr_fk") REFERENCES "Users"("id_usr_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "WorkOrder"
ADD FOREIGN KEY("id_eds_fk") REFERENCES "EDS"("id_eds_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "WorkOrder"
ADD FOREIGN KEY("id_question_form_fk") REFERENCES "FormQuestions"("id_question_form_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "FormAnswers"
ADD FOREIGN KEY("id_question_form_fk") REFERENCES "FormQuestions"("id_question_form_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Users"
ADD FOREIGN KEY("id_work_area_fk") REFERENCES "WorkArea"("id_work_area_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "WorkOrder"
ADD FOREIGN KEY("id_work_area_fk") REFERENCES "WorkArea"("id_work_area_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;