CREATE TABLE "Users" (
	"id_usr_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100),
	"email" VARCHAR(100),
	"password" VARCHAR(255),
	"usr_status" BOOLEAN DEFAULT TRUE,
	"id_role_fk" INTEGER,
	"id_eds_fk" INTEGER,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id_usr_pk"),
	UNIQUE("email")
);




CREATE TABLE "Roles" (
	"id_rol_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50),
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"id_permission_fk" INTEGER,
	"role_status" BOOLEAN DEFAULT TRUE,
	PRIMARY KEY("id_rol_pk")
);




CREATE TABLE "Permissions" (
	"id_permissions_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50),
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"permission_status" BOOLEAN DEFAULT TRUE,
	PRIMARY KEY("id_permissions_pk")
);




CREATE TABLE "WorkOrder" (
	"id_work_order_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"status" VARCHAR(20) DEFAULT 'pending',
	"id_usr_fk" INTEGER,
	"id_eds_fk" INTEGER,
	"dsc" TEXT,
	"image" VARCHAR(255),
	"id_question_form_fk" INTEGER,
	"name" VARCHAR(100),
	PRIMARY KEY("id_work_order_pk")
);




CREATE TABLE "EDS" (
	"id_eds_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(65),
	"id_plaza_fk" INTEGER,
	PRIMARY KEY("id_eds_pk")
);




CREATE TABLE "Plaza" (
	"id_plaza_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(20),
	"state" VARCHAR(20),
	"municipality" VARCHAR(35),
	"zip_code" VARCHAR(10),
	"plaza_status" BOOLEAN,
	"plaza_phone" INTEGER,
	PRIMARY KEY("id_plaza_pk")
);




CREATE TABLE "FormQuestions" (
	"id_question_form_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"question" VARCHAR(65),
	"is_required" BOOLEAN,
	"type" VARCHAR(65),
	PRIMARY KEY("id_question_form_pk")
);




CREATE TABLE "FormAnswers" (
	"id_answer_form_pk" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_question_form_fk" INTEGER,
	"answer" VARCHAR(65),
	PRIMARY KEY("id_answer_form_pk")
);



ALTER TABLE "Users"
ADD FOREIGN KEY("id_role_fk") REFERENCES "Roles"("id_rol_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Roles"
ADD FOREIGN KEY("id_permission_fk") REFERENCES "Permissions"("id_permissions_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Users"
ADD FOREIGN KEY("id_eds_fk") REFERENCES "EDS"("id_eds_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "EDS"
ADD FOREIGN KEY("id_plaza_fk") REFERENCES "Plaza"("id_plaza_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "WorkOrder"
ADD FOREIGN KEY("id_usr_fk") REFERENCES "Users"("id_usr_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "WorkOrder"
ADD FOREIGN KEY("id_eds_fk") REFERENCES "EDS"("id_eds_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "WorkOrder"
ADD FOREIGN KEY("id_question_form_fk") REFERENCES "FormQuestions"("id_question_form_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "FormAnswers"
ADD FOREIGN KEY("id_question_form_fk") REFERENCES "FormQuestions"("id_question_form_pk")
ON UPDATE NO ACTION ON DELETE NO ACTION;